In [3]:
import numpy as np

In [4]:
a = np.array([1,2])

In [5]:
b = np.array([2,1])

In [6]:
z=np.log(a)

In [7]:
print(z)

[0.         0.69314718]


In [8]:
z=np.exp(a)

In [9]:
print(z)

[2.71828183 7.3890561 ]


In [10]:
z=np.sqrt(a)

In [11]:
print(z)

[1.         1.41421356]


In [12]:
np.dot(a,b)

4

In [13]:
z=np.dot(a,b)


In [14]:
z=a.dot(b)

In [15]:
print(z)

4


In [17]:
z=np.linalg.norm(a)

In [18]:
print(a)

[1 2]


In [19]:
cosangle=a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [20]:
print(cosangle)

0.7999999999999998


In [21]:
angle=np.arccos(cosangle)

In [22]:
print(angle)

0.6435011087932847


In [23]:
a=np.matrix([[1,2,3],[4,5,6]])

In [24]:
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
print(a[0,0])

1


In [26]:
x=np.array(a)

In [27]:
print(x)

[[1 2 3]
 [4 5 6]]


In [30]:
print(x[1,0])

4


In [31]:
print(a[1,2])

6


In [33]:
print(x.T)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
z=np.zeros(5)

In [35]:
print(z)

[0. 0. 0. 0. 0.]


In [37]:
m=np.zeros((2,2))

In [38]:
print(m)

[[0. 0.]
 [0. 0.]]


In [39]:
o=np.ones((3,3))

In [40]:
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
r=np.random.random((2,2))

In [42]:
print(r)

[[0.62282991 0.86765214]
 [0.83951051 0.23593344]]


In [44]:
h=np.random.randn(2,2)

In [45]:
print(h)

[[ 0.35760285 -0.32942817]
 [ 0.83890899  0.5685881 ]]


In [46]:
print(h.mean())

0.3589179406669659


In [47]:
print(h.var())

0.18704377042257062


In [49]:
p=np.array([[1,2,3],[2,2,1],[6,7,9]])

In [50]:
q=np.array([[4,5],[6,7],[6,8]])

In [51]:
r=p.dot(q)

In [52]:
print(r)

[[ 34  43]
 [ 26  32]
 [120 151]]


In [53]:
pinv=np.linalg.inv(p)

In [54]:
print(pinv)

[[-1.57142857 -0.42857143  0.57142857]
 [ 1.71428571  1.28571429 -0.71428571]
 [-0.28571429 -0.71428571  0.28571429]]


In [55]:
correct=p.dot(pinv)

In [56]:
print(correct)

[[ 1.00000000e+00 -2.22044605e-16  5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00  5.55111512e-17]
 [ 1.38777878e-15  1.11022302e-15  1.00000000e+00]]


In [57]:
d=np.linalg.det(p)

In [58]:
print(d)

-6.999999999999999


In [59]:
di=np.diag(p)

In [60]:
print(di)

[1 2 9]


In [61]:
x=np.diag([1,2,3,4])

In [62]:
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [63]:
x=np.trace(x)

In [64]:
print(x)

10
